/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VestidosRouteImport } from './routes/vestidos'
import { Route as SobMedidaRouteImport } from './routes/sob-medida'
import { Route as OuterwearRouteImport } from './routes/outerwear'
import { Route as CasualRouteImport } from './routes/casual'
import { Route as AlfaiatariaRouteImport } from './routes/alfaiataria'
import { Route as IndexRouteImport } from './routes/index'

const VestidosRoute = VestidosRouteImport.update({
  id: '/vestidos',
  path: '/vestidos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobMedidaRoute = SobMedidaRouteImport.update({
  id: '/sob-medida',
  path: '/sob-medida',
  getParentRoute: () => rootRouteImport,
} as any)
const OuterwearRoute = OuterwearRouteImport.update({
  id: '/outerwear',
  path: '/outerwear',
  getParentRoute: () => rootRouteImport,
} as any)
const CasualRoute = CasualRouteImport.update({
  id: '/casual',
  path: '/casual',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfaiatariaRoute = AlfaiatariaRouteImport.update({
  id: '/alfaiataria',
  path: '/alfaiataria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alfaiataria': typeof AlfaiatariaRoute
  '/casual': typeof CasualRoute
  '/outerwear': typeof OuterwearRoute
  '/sob-medida': typeof SobMedidaRoute
  '/vestidos': typeof VestidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alfaiataria': typeof AlfaiatariaRoute
  '/casual': typeof CasualRoute
  '/outerwear': typeof OuterwearRoute
  '/sob-medida': typeof SobMedidaRoute
  '/vestidos': typeof VestidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alfaiataria': typeof AlfaiatariaRoute
  '/casual': typeof CasualRoute
  '/outerwear': typeof OuterwearRoute
  '/sob-medida': typeof SobMedidaRoute
  '/vestidos': typeof VestidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alfaiataria'
    | '/casual'
    | '/outerwear'
    | '/sob-medida'
    | '/vestidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alfaiataria'
    | '/casual'
    | '/outerwear'
    | '/sob-medida'
    | '/vestidos'
  id:
    | '__root__'
    | '/'
    | '/alfaiataria'
    | '/casual'
    | '/outerwear'
    | '/sob-medida'
    | '/vestidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlfaiatariaRoute: typeof AlfaiatariaRoute
  CasualRoute: typeof CasualRoute
  OuterwearRoute: typeof OuterwearRoute
  SobMedidaRoute: typeof SobMedidaRoute
  VestidosRoute: typeof VestidosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vestidos': {
      id: '/vestidos'
      path: '/vestidos'
      fullPath: '/vestidos'
      preLoaderRoute: typeof VestidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sob-medida': {
      id: '/sob-medida'
      path: '/sob-medida'
      fullPath: '/sob-medida'
      preLoaderRoute: typeof SobMedidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outerwear': {
      id: '/outerwear'
      path: '/outerwear'
      fullPath: '/outerwear'
      preLoaderRoute: typeof OuterwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casual': {
      id: '/casual'
      path: '/casual'
      fullPath: '/casual'
      preLoaderRoute: typeof CasualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfaiataria': {
      id: '/alfaiataria'
      path: '/alfaiataria'
      fullPath: '/alfaiataria'
      preLoaderRoute: typeof AlfaiatariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlfaiatariaRoute: AlfaiatariaRoute,
  CasualRoute: CasualRoute,
  OuterwearRoute: OuterwearRoute,
  SobMedidaRoute: SobMedidaRoute,
  VestidosRoute: VestidosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
